### ISSUE TITLE
Initializing texture for hardware decoding failed 

### ISSUE THREAD

**Issue by mokkurkalve** [haasn/libplacebo#98] opened 2021-04-29 18:59 UTC
( I've sent this bug rapport to Arch Linux first. They asked me to bring it upstream. https://bugs.archlinux.org/task/70626 )

Description:
Playing h264 video vith mpv 0.33.1 compiled against libplacebo 3.120.2 with following options
--volume-max=120 --vd-lavc-threads=8 --hwdec=auto --vo=gpu --gpu-api=vulkan --gpu-context=x11vk --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp --video-sync=display-resample --interpolation --tscale=oversample --ao=pulse
result in just a blue screen.
Downgrading libplacebo to 3.104.0 and compiling mpv 0.33.1 against that makes the video play right again with same options.

These are the error messages mpv throws with libplacebo 3.120.2:

(+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
(+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu/vulkan/libplacebo] DRM modifier INTEL 0x2 not available for format r8. Ignoring, but expect possible corruption. Available modifiers:
[vo/gpu/vulkan/libplacebo] INVALID
[vo/gpu/vulkan/libplacebo] LINEAR
[vo/gpu/vulkan/libplacebo] Using legacy hacks for DMA buffers without modifiers. May result in corruption!
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 vaapi[nv12]
[vo/gpu/vaapi-egl] unsupported VA image format nv12
[vo/gpu] Initializing texture for hardware decoding failed.
AV: 00:00:10 / 00:16:42 (1%) A-V: 0.004 DS: 2.500/1

The same video with libplacebo 3.104.0 (now working fine) :

(+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
(+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
Using hardware decoding (vaapi-copy).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 nv12
AV: 00:00:17 / 00:16:42 (2%) A-V: -0.004 DS: 2.500/2

**Comment by haasn** [comment] 2021-04-29 20:30
Just to be sure, can you try again on a version of the intel driver new enough to have VK_EXT_image_drm_format_modifier?

But otherwise, this seems like a possible duplicate of https://code.videolan.org/videolan/libplacebo/-/issues/147

**Comment by mokkurkalve** [comment] 2021-04-29 22:25
I reckon you mean intel-media-driver? Arch Linux have version 21.1.3, which are quite new. But I now replaced these with fresh -git versions:
intel-media-driver -> 2021.2.0.r64.g3ed742047
intel-gmmlib -> 21.1.2.r0.gcac1a15
libva -> 2.11.0.pre1.r5.gfb31fe6
And compiled mpv 0.33.1 against libplacebo 3.120.2
But it was the same result; monocrome blue instead of video and the same error messages.
Downgrading libplacebo to 3.104.0 and compiling mpv against that again solved the issue, video works.
BTW, should I also compile libplacebo locally? I use the packages from Arch here.

**Comment by haasn** [comment] 2021-04-30 08:48
> Downgrading libplacebo to 3.104.0 and compiling mpv against that again solved the issue, video works.

Oh, that's useful. Can you bisect it to an exact commit?

**Comment by juxuanu** [comment] 2021-05-02 14:18
I'm having a similar issue that started after upgrading libplacebo (3.104.0-2 -> 3.120.2-1). I compiled both libplacebo and mpv. 

Versions are:
- libplacebo: 3.120.2
- mpv: 0.33.1

The error:
```
[vo/gpu/vulkan/libplacebo] Using legacy hacks for DMA buffers without modifiers. May result in corruption!
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
The imported image has smaller dimensions than the internal
dimensions. Using it is going to fail badly, so we reject
this import.
(internal dimensions: 128 x 128, external dimensions: 64 x 64)
[vo/gpu/vulkan/libplacebo] vk->AllocateMemory(vk->dev, &ainfo, PL_VK_ALLOC, &vkmem): VK_ERROR_INVALID_EXTERNAL_HANDLE (../src/vulkan/malloc.c:761)
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [gpu] 1920x800 vaapi[nv12]
[vo/gpu/vaapi-egl] unsupported VA image format nv12
[vo/gpu] Initializing texture for hardware decoding failed.
```

The audio plays fine.

This is not present when not using hardware acceleration (`mpv --hwdec=none`).

I'm not familiar with bisecting. Should I be compiling libplacebo and then mpv for each try? I only own a laptop which I think would make this work tedious.

**Comment by haasn** [comment] 2021-05-03 21:06
@juxuanu for your issue, can you check this patch?

```diff
diff --git a/src/vulkan/gpu.c b/src/vulkan/gpu.c
index de3980f..5f5d405 100644
--- a/src/vulkan/gpu.c
+++ b/src/vulkan/gpu.c
@@ -1126,7 +1126,7 @@ static const struct pl_tex *vk_tex_create(const struct pl_gpu *gpu,
 
     VkPhysicalDeviceExternalImageFormatInfoKHR ext_pinfo = {
         .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO_KHR,
-        .pNext = handle_type == PL_HANDLE_DMA_BUF ? &drm_pinfo : NULL,
+        .pNext = (handle_type == PL_HANDLE_DMA_BUF && has_drm_mods) ? &drm_pinfo : NULL,
         .handleType = ext_info.handleTypes,
     };
 
```

That should revert the logic to be 100% identical to the logic in v3.104.0. Inspection of the git diff reveals that the addition of this extra struct which *should* be ignored by the driver, but probably isn't (driver bug!). If this change fixes it, I might consider that work-around.

**Comment by haasn** [comment] 2021-05-03 21:09
Oh, I realized something entirely different. There was another change in behavior, not in libplacebo, but in *mpv*, and it's this line:

```c
        struct pl_tex_params tex_params = {
            .w = mp_image_plane_w(&p->layout, n),
            .h = mp_image_plane_h(&p->layout, n),
            .d = 0,
            .format = format->priv,
            .sampleable = true,
            .sample_mode = format->linear_filter ? PL_TEX_SAMPLE_LINEAR
                                                 : PL_TEX_SAMPLE_NEAREST,
            .import_handle = PL_HANDLE_DMA_BUF,
            .shared_mem = (struct pl_shared_mem) {
                .handle = {
                    .fd = fd,
                },
                .size = size,
                .offset = offset,
#if PL_API_VER >= 88
                .drm_format_mod = p->desc.objects[id].drm_format_modifier,
#endif
#if PL_API_VER >= 106
                .stride_w = pitch,
#endif
            },
        };
```

Note that the texture stride option was added in libplacebo 3.106.0, so 3.104.0 effectively still passes no stride for this function call. Maybe removing *that* line will fix it for you?

**Comment by haasn** [comment] 2021-05-03 21:17
Also, @mokkurkalve I just noticed something *very* important in your working log from v3.104.0:

> Using hardware decoding (**vaapi-copy**).

Contrast this with your non-working log, where it's using **vaapi**, not vaapi-copy. I'm going to assume that vaapi-copy still works, and the actual issue in your case is that libplacebo is erroneously advertising support for direct hwdec even though it doesn't work?

**Closed** 2021-05-03 22:00 UTC

**Comment by juxuanu** [comment] 2021-05-03 23:26
@haasn You are correct. `vaapi-copy` works, `vaapi` spits the errors described above.
