### ISSUE TITLE
export pl_opengl_wrap_fb

### ISSUE THREAD

**Issue by akvadrako** [haasn/libplacebo#81] opened 2020-07-08 13:06 UTC
While integrating libplacebo, I would like render directly to an externally created fbo.

The `pl_opengl_wrap_fb` function is what I need, but it's currently private. It would be nice if it was exposed along with `pl_opengl_wrap`.

**Comment by haasn** [comment] 2020-07-08 14:45
Duplicate of https://code.videolan.org/videolan/libplacebo/-/issues/80

Should be relatively straightforward, I just didn't get around to it since nobody needed it yet. I'll do it hopefully soon(ish). Thanks for the suggestion.

**Comment by haasn** [comment] 2020-07-08 14:48
Never mind, I see what you're asking. You want specifically the ability to wrap a raw framebuffer without associated image.

I'll implement it, though probably not by exposing `gl_opengl_wrap_fb` as-is but by adding an extra framebuffer argument to the `pl_opengl_wrap` function (and making the texture itself optional).

**Comment by akvadrako** [comment] 2020-07-08 15:02
Sounds good to me :+1:

**Closed** 2020-07-09 13:31 UTC
