### ISSUE TITLE
MSVC: Linking against libplacebo DLL created by mingw

### ISSUE THREAD

**Issue by neevek** [haasn/libplacebo#176] opened 2023-06-26 08:27 UTC
Hi, haasn, Thanks for the great work!

I intend to use libplacebo in my project, which is built with MSVC, I tried building libplacebo using MSVC but failed with quite a few errors due to C language syntax issues, I switched to mingw, it succeeded, I got the DLL and the associated import library (the `.lib` file).

When I run my program, I found that addresses of all libplacebo functions are correct, I can call all the functions without error, but `extern struct`s like `pl_color_space_hdr10`, `pl_color_map_default_params` all contain garbage, taking addresses of these structs reveals that they are not pointing to the expected `rdata` section of the DLL, their addresses are next to functions like `pl_shader_color_map`.  

I tried putting `__declspec(dllimport)` before those `extern struct`s, and it just WORKS! Like the following change in the `colorspace.h` file:

```c
__declspec(dllimport) extern const struct pl_color_space pl_color_space_hdr10;
```

I am not that familiar with those windows related import/export stuff, what should I do to contribute to this issue? Is it ok for me to define a macro for adding that `dllimport` on Windows and make a PR?

**Comment by kasper93** [comment] 2023-06-26 14:23
> I intend to use libplacebo in my project, which is built with MSVC, I tried building libplacebo using MSVC but failed with quite a few errors due to C language syntax issues, I switched to mingw, it succeeded, I got the DLL and the associated import library (the .lib file).

Indeed, MSVC build is not supported, there are few thinks like `__typeof__` that are incompatible with MSVC and there is no plan to change it.

I would suggest using clang (x86_64-pc-windows-msvc) which is shipped with Microsoft build tools. While MinGW-w64 is also a valid option, native Windows SDK clang build is better for various reasons... that I don't want to talk about here.

> When I run my program, I found that addresses of all libplacebo functions are correct, I can call all the functions without error, but extern structs like pl_color_space_hdr10, pl_color_map_default_params all contain garbage, taking addresses of these structs reveals that they are not pointing to the expected rdata section of the DLL, their addresses are next to functions like pl_shader_color_map.

Yes, indeed. There were changes to support shared library building on Windows in this release cycle. It will work correctly on current master (also v6.287.0-rc1) and next release.

> I am not that familiar with those windows related import/export stuff, what should I do to contribute to this issue? Is it ok for me to define a macro for adding that dllimport on Windows and make a PR?

It would be, but lucky for you it is already done :)

**Comment by neevek** [comment] 2023-06-27 08:34
Hi @kasper93, I just tried `v6.287.0-rc1` on Windows, it compiles fine, only with a small issue at runtime that I can address on my side, when compiling the generated GLSL shader at runtime, the shader compiler complains with the following:

```
'sampler3D' : declaration must include a precision qualifier for type
```

I can add the following before the generated shader, and it compiles:
```
precision mediump sampler3D;
```

Another thing that I am not sure if it is an issue, after upgrading from `v5.264.1` to `v6.287.0-rc1`, HDR video rendered with the generated shader is more saturated and appears far more yellowish.

**Comment by kasper93** [comment] 2023-06-29 01:50
> Hi @kasper93, I just tried `v6.287.0-rc1` on Windows, it compiles fine, only with a small issue at runtime that I can address on my side, when compiling the generated GLSL shader at runtime, the shader compiler complains with the following:
> 
> ```
> 'sampler3D' : declaration must include a precision qualifier for type
> ```
> 
> I can add the following before the generated shader, and it compiles:
> 
> ```
> precision mediump sampler3D;
> ```

What target are we talking about? 

Precision is added if needed/supported
https://github.com/haasn/libplacebo/blob/8ceb7a544b70aff7e432cbb9708666115a6cb985/src/dispatch.c#L403-L404

Could you attach full log with more info so we can understand why it fails?

> Also, now it requires `vulkan` even if I specify `-Dvulkan=disabled`, so I have to enable it though I don't use vulkan in my case.

Building libplacebo without Vulkan headers is not supported, `vulkan/stub.c` requires the headers. I made a small fix because non-standard location headers were not added as dependency for `stub.c` https://code.videolan.org/videolan/libplacebo/-/merge_requests/484 Should help, or not, depends on your buildsystem.

> Another thing that I am not sure if it is an issue, after upgrading from `v5.264.1` to `v6.287.0-rc1`, HDR video rendered with the generated shader is more saturated and appears far more yellowish. the tone mapping function is `pl_tone_map_hable`, and all other stuff are just default settings, why is it more saturated now?

There were a lot changes to tone mapping and it is expected that you see differences. You probably should look into new options and features to configure it correctly for your needs.

Also there is a patch in-flight that improves TM quite a bit in some cases. https://code.videolan.org/videolan/libplacebo/-/merge_requests/481 should be merged soon.

**Comment by neevek** [comment] 2023-06-30 03:42
> What target are we talking about?
> 
> Precision is added if needed/supported
> 
> https://github.com/haasn/libplacebo/blob/8ceb7a544b70aff7e432cbb9708666115a6cb985/src/dispatch.c#L403-L404

`sampler3D` is a uniform generated here:

https://github.com/haasn/libplacebo/blob/f06efc75bf1cd39c3520339e9420cab98b451aa6/src/shaders/colorspace.c#L1892
https://github.com/haasn/libplacebo/blob/f06efc75bf1cd39c3520339e9420cab98b451aa6/src/shaders/lut.c#L339

This will add a `pl_shader_desc` to `pl_shader->descs`, it is a `sampler3D` because `dims` is 3  in the code above. I only use `pl_opengl_create` and `pl_shader_color_map` to generate shaders, and in my case I don't see it reaches the code you quoted, I can see `pl_dispatch_create` is called but all other code in the `dispatch.c` file is not run, maybe it's because I don't use libplacebo to render.

> Building libplacebo without Vulkan headers is not supported, `vulkan/stub.c` requires the headers. I made a small fix because non-standard location headers were not added as dependency for `stub.c` https://code.videolan.org/videolan/libplacebo/-/merge_requests/484 Should help, or not, depends on your buildsystem.

With this change, now I can build with `-Dvulkan=disabled`, and the result artifact is about 20% smaller.

> > Another thing that I am not sure if it is an issue, after upgrading from `v5.264.1` to `v6.287.0-rc1`, HDR video rendered with the generated shader is more saturated and appears far more yellowish. the tone mapping function is `pl_tone_map_hable`, and all other stuff are just default settings, why is it more saturated now?
> 
> There were a lot changes to tone mapping and it is expected that you see differences. You probably should look into new options and features to configure it correctly for your needs.

Yes, I increased `hybrid_mix` and set it to `2.5`, the color is much better, but I am not sure what other things will be affected by this setting.

By the way, when will the next version be released? I see a lot of awesome work you guys have commit to the master branch.

**Comment by haasn** [comment] 2023-06-30 12:56
This is all expected behavior. libplacebo can't add the necessary preamble for you, unless you're going through the `pl_dispatch`, because it doesn't see the rest of the shader.

Though if you want, I could expose a function to allow generating the requirements for a given `pl_shader`?

**Comment by neevek** [comment] 2023-06-30 13:53
> Though if you want, I could expose a function to allow generating the requirements for a given `pl_shader`?

It will be great, with OpenGLES, `precision highp float;` is also required.

> New release will be very soon :)

Looking forward to the new release.

**Comment by neevek** [comment] 2023-07-05 02:25
> > There were a lot changes to tone mapping and it is expected that you see differences. You probably should look into new options and features to configure it correctly for your needs.
> 
> Yes, I increased `hybrid_mix` and set it to `2.5`, the color is much better, but I am not sure what other things will be affected by this setting.

Regarding the "more saturated" issue, I found that `hybrid_mix` is removed in the latest RC version, what options do I need to tweak to desaturate the color in the recent release?

**Comment by kasper93** [comment] 2023-08-02 12:17
I think this issue can be closed?

**Comment by neevek** [comment] 2023-08-02 13:26
> I think this issue can be closed? I don't see anything remaining here.

Yes, this can be closed now.
I used `pl_tone_map_st2094_10`, and lowering the param a little bit, the color is quite good.

**Closed** 2023-08-02 14:14 UTC
