### ISSUE TITLE
One file doesn't compile with ffmpeg-git

### ISSUE THREAD

**Issue by arzeth** [haasn/libplacebo#106] opened 2021-09-02 07:57 UTC
Arch Linux [testing], ffmpeg-git, shaderc-git, glslang-git, gcc 11.1.0.
### Log
```
[81/128] Compiling C object demos/plplay.p/plplay.c.o
FAILED: demos/plplay.p/plplay.c.o 
cc -Idemos/plplay.p -Idemos -I../demos -I../src/include -I../src/include/dummy -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c99 -Wundef -Wshadow -Wparentheses -Wpointer-arith -D_ISOC99_SOURCE -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -U__STRICT_ANSI__ -fvisibility=hidden -Wmissing-prototypes -Wno-pointer-sign -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-type-limits -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -g -pipe -march=native -mtune=native -O2 -ftree-vectorize -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -pthread -MD -MQ demos/plplay.p/plplay.c.o -MF demos/plplay.p/plplay.c.o.d -o demos/plplay.p/plplay.c.o -c ../demos/plplay.c
In file included from ../src/include/libplacebo/utils/libav.h:136,
                 from ../demos/plplay.c:33:
../src/include/libplacebo/utils/libav_internal.h: In function ‘pl_frame_from_avframe’:
../src/include/libplacebo/utils/libav_internal.h:525:9: warning: enumeration value ‘AV_FILM_GRAIN_PARAMS_H274’ not handled in switch [-Wswitch]
  525 |         switch (fgp->type) {
      |         ^~~~~~
../demos/plplay.c: In function ‘init_codec’:
../demos/plplay.c:165:30: error: implicit declaration of function ‘av_cpu_count’; did you mean ‘av_popcount’? [-Werror=implicit-function-declaration]
  165 |     p->codec->thread_count = av_cpu_count();
      |                              ^~~~~~~~~~~~
      |                              av_popcount
cc1: some warnings being treated as errors
[85/128] Generating vulkan boilerplate with a custom command
Found vk.xml: /usr/share/vulkan/registry/vk.xml
[86/128] Compiling C++ object src/libplacebo.so.120.p/glsl_glslang.cc.o
ninja: build stopped: subcommand failed.
```

### Solution
Add
```
#include <libavutil/cpu.h>
```
then everything compiles and works for me.

### Why it broke

`demos/plplay.c` includes `libavcodec/avcodec.h` which stopped including `libavutil/cpu.h` since https://github.com/FFmpeg/FFmpeg/commit/69f120ead7fbec9a469a5c0950b2a44fbc89f7a0

### By the way
If you wonder about the warning (`AV_FILM_GRAIN_PARAMS_H274`), then it's because `H.274 film grain` was added ~10 days ago in FFmpeg.

**Comment by haasn** [comment] 2021-09-02 08:21
Duplicate of #105

**Closed by haasn** 2021-09-02 08:21 UTC
